services:
  - type: web
    name: colour-palette-generator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free # Optional: defaults to free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9 # Specify a full patch version 